--- 
- 
  become: true
  become_user: root
  hosts: aws_ec2
  remote_user: ec2-user
  tasks:
    - name: "activate epel"
      command : amazon-linux-extras install epel -y 
    - 
      name: "yum update"
      yum: 
        name: "*"
        state: latest
    - 
      get_url: 
        dest: /etc/yum.repos.d/jenkins.repo
        url: "https://pkg.jenkins.io/redhat-stable/jenkins.repo"
      name: "Download Long Term Jenkins release"
    - 
      ansible.builtin.rpm_key: 
        key: "https://pkg.jenkins.io/redhat-stable/jenkins.io.key"
        state: present
      name: "Import jenkins key from url"
   
    - name: "install git"
      yum: name=git state=present

    - name: "Install docker"
      yum: name=docker state=present
  
    - name: "start docker"
      service: name=docker state=started enabled=yes
    - 
      name: "Install jenkins"
      yum: 
        name: jenkins
        state: latest
    - 
      name: "Install java"
      yum: 
        name: java-1.8.0-openjdk-devel
        state: present
    - 
      ansible.builtin.systemd: 
        daemon_reload: true
      name: "daemon-reload to pick up config changes"
    - 
      ansible.builtin.systemd: 
        name: jenkins
        state: started
      name: "Start jenkins"

    - name: "add jenkins users to Docker Group"
      command: usermod -aG docker jenkins

    - name: "retart jenkins"
      command: systemctl restart jenkins.service

    - name: "install kubectl"
      get_url: url=https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl dest=./kubectl
    
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /home/ec2-user/bin
        state: directory
        mode: '0755'

    - name: "Copy the binary to a folder in your PATH"
      copy: remote_src=True src=./kubectl dest=/home/ec2-user/bin/kubectl

    - name: "Apply execute permissions to the binary"
      shell: chmod +x /home/ec2-user/bin/kubectl

    - name : "update path"
      shell: echo "export PATH=$PATH:/home/ec2-user/bin" > /etc/environment

    - name: Create tmp directory if it does not exist
      ansible.builtin.file:
        path: /tmp
        state: directory
        mode: '0755'

#    - name: "install eksctl"
#      get_url: url=https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz dest=/tmp/eksctl

#    - name: "untar eksctl package"
#      shell: chdir=/tmp untar

    - name: "install eksctl"
      shell: curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp

    - name: "extracted binary to /usr/local/bin"
      command: mv /tmp/eksctl /usr/local/bin

    - name : "update path"
      shell: echo "export PATH=$PATH:/usr/local/bin/" > /etc/environment

